[package]
name = "crates-packages-modules"
version = "0.1.0"
authors = ["olliurban <oliver.urbaniak@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
